galaxy_info:
  author: XLAB Steampunk <steampunk@xlab.si>
  description: Install Sensu Go components
  license: GPL-3.0-or-later
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - "6"
        - "7"
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
        - disco dingo

  galaxy_tags:
    - sensu
